site_name: GeneWeaver
theme:
  name: material
  logo: assets/GW2-logo.png
  favicon: assets/GW2-logo.png
  icon:
    repo: fontawesome/brands/git-alt
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: geneweaver
      media: "(prefers-color-scheme: light)"
#      primary: green
#      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: blue grey
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
#    - navigation.tabs
    - navigation.sections
#    - navigation.expand
    - navigation.indexes
  #    - navigation.tabs.sticky
  #    - header.autohide
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
extra_css:
  - stylesheets/extra.css
repo_name: bergsalex/geneweaver-docs
repo_url: https://github.com/bergsalex/geneweaver-docs
edit_uri: edit/main/docs/
extra:
  generator: true
markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - mkdocs-jupyter
nav:
  - Home: index.md
  - Getting Started:
      - getting-started/index.md
      - Foundational Concepts: getting-started/foundational-concepts.md
      - Web Application: getting-started/web-application.md
      - Command Line Interface: getting-started/command-line-interface.md
      - Running Tools Locally: getting-started/running-tools-locally.md
#      - Contributing to Packages: getting-started/contributing-to-packages.md
#      - Contributing to Documentation: getting-started/contributing-to-documentation.md
  - Concepts:
      - concepts/index.md
      - Genes and GeneSets: concepts/genes-and-genesets.md
      - External Source Data: concepts/geneweaver-data.md
      - Geneweaver Data Model: concepts/geneweaver-data-model.md
      - Package Based Architecture: concepts/package-based-architecture.md
  - Tutorial:
      - tutorial/index.md
      - NCI-60 Example Workflow: tutorial/nci_60_example_01.ipynb
#      - Accessing Geneweaver Data: tutorial/accessing-geneweaver-data.md
#      - Running a Local Database: tutorial/running-a-local-database.md
#      - Creating New Tools: tutorial/creating-new-tools.md
#      - Testing New Tools: tutorial/testing-new-tools.md
#      - Exploring Data in Javascript: tutorial/exploring-data-in-javascript.md
#      - Creating Documentation Sites: tutorial/creating-a-new-documentation-site.md
  - Reference:
      - reference/index.md
      - Available Packages: reference/available-packages.md
      - Available Tools: reference/available-tools.md
      - Scientific Workflows: reference/scientific-workflows.md
      - Data Model: reference/data-model.md
      - GeneSet Tiers: reference/geneset-tiers.md
      - Contributing Guide: reference/contributing-guide.md
      - Development Guide: reference/development-guide.md
      - ReST API: reference/restful-api.md
      - Acknowledgements: reference/acknowledgements.md
